FROM httpd:2.4

COPY ./public_html/ /usr/local/apache2/htdocs/

# Fix configs for OpenShift (non-root friendly)
RUN sed -i 's/Listen 80/Listen 8080/' /usr/local/apache2/conf/httpd.conf \
    && echo "ServerName localhost" >> /usr/local/apache2/conf/httpd.conf \
    && sed -i 's#PidFile "logs/httpd.pid"#PidFile "/tmp/httpd.pid"#' /usr/local/apache2/conf/extra/httpd-default.conf

EXPOSE 8080

